---
version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres_11_tt
    ports:
      - "54321:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
